/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char91indexChar93RouteImport } from './routes/[index]'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PostsIndexRouteImport } from './routes/posts.index'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as AdminUsersRouteImport } from './routes/_admin.users'
import { Route as PostsPostIdEditRouteImport } from './routes/posts.$postId.edit'
import { Route as AdminSettingsProfileRouteImport } from './routes/_admin.settings.profile'
import { Route as OrgsOrgIdUsersUserIdRouteImport } from './routes/orgs.$orgId.users.$userId'

const Char91indexChar93Route = Char91indexChar93RouteImport.update({
  id: '/index',
  path: '/index',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsIndexRoute = PostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PostsRoute,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => PostsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const PostsPostIdEditRoute = PostsPostIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PostsPostIdRoute,
} as any)
const AdminSettingsProfileRoute = AdminSettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => AdminRoute,
} as any)
const OrgsOrgIdUsersUserIdRoute = OrgsOrgIdUsersUserIdRouteImport.update({
  id: '/orgs/$orgId/users/$userId',
  path: '/orgs/$orgId/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/index': typeof Char91indexChar93Route
  '/posts': typeof PostsRouteWithChildren
  '/users': typeof AdminUsersRoute
  '/posts/$postId': typeof PostsPostIdRouteWithChildren
  '/posts/': typeof PostsIndexRoute
  '/settings/profile': typeof AdminSettingsProfileRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/orgs/$orgId/users/$userId': typeof OrgsOrgIdUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/index': typeof Char91indexChar93Route
  '/users': typeof AdminUsersRoute
  '/posts/$postId': typeof PostsPostIdRouteWithChildren
  '/posts': typeof PostsIndexRoute
  '/settings/profile': typeof AdminSettingsProfileRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/orgs/$orgId/users/$userId': typeof OrgsOrgIdUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/about': typeof AboutRoute
  '/index': typeof Char91indexChar93Route
  '/posts': typeof PostsRouteWithChildren
  '/_admin/users': typeof AdminUsersRoute
  '/posts/$postId': typeof PostsPostIdRouteWithChildren
  '/posts/': typeof PostsIndexRoute
  '/_admin/settings/profile': typeof AdminSettingsProfileRoute
  '/posts/$postId/edit': typeof PostsPostIdEditRoute
  '/orgs/$orgId/users/$userId': typeof OrgsOrgIdUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/index'
    | '/posts'
    | '/users'
    | '/posts/$postId'
    | '/posts/'
    | '/settings/profile'
    | '/posts/$postId/edit'
    | '/orgs/$orgId/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/index'
    | '/users'
    | '/posts/$postId'
    | '/posts'
    | '/settings/profile'
    | '/posts/$postId/edit'
    | '/orgs/$orgId/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/about'
    | '/index'
    | '/posts'
    | '/_admin/users'
    | '/posts/$postId'
    | '/posts/'
    | '/_admin/settings/profile'
    | '/posts/$postId/edit'
    | '/orgs/$orgId/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AboutRoute: typeof AboutRoute
  Char91indexChar93Route: typeof Char91indexChar93Route
  PostsRoute: typeof PostsRouteWithChildren
  OrgsOrgIdUsersUserIdRoute: typeof OrgsOrgIdUsersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index': {
      id: '/index'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof Char91indexChar93RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/': {
      id: '/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof PostsIndexRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/posts/$postId/edit': {
      id: '/posts/$postId/edit'
      path: '/edit'
      fullPath: '/posts/$postId/edit'
      preLoaderRoute: typeof PostsPostIdEditRouteImport
      parentRoute: typeof PostsPostIdRoute
    }
    '/_admin/settings/profile': {
      id: '/_admin/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AdminSettingsProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/orgs/$orgId/users/$userId': {
      id: '/orgs/$orgId/users/$userId'
      path: '/orgs/$orgId/users/$userId'
      fullPath: '/orgs/$orgId/users/$userId'
      preLoaderRoute: typeof OrgsOrgIdUsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminSettingsProfileRoute: typeof AdminSettingsProfileRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminSettingsProfileRoute: AdminSettingsProfileRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PostsPostIdRouteChildren {
  PostsPostIdEditRoute: typeof PostsPostIdEditRoute
}

const PostsPostIdRouteChildren: PostsPostIdRouteChildren = {
  PostsPostIdEditRoute: PostsPostIdEditRoute,
}

const PostsPostIdRouteWithChildren = PostsPostIdRoute._addFileChildren(
  PostsPostIdRouteChildren,
)

interface PostsRouteChildren {
  PostsPostIdRoute: typeof PostsPostIdRouteWithChildren
  PostsIndexRoute: typeof PostsIndexRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsPostIdRoute: PostsPostIdRouteWithChildren,
  PostsIndexRoute: PostsIndexRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AboutRoute: AboutRoute,
  Char91indexChar93Route: Char91indexChar93Route,
  PostsRoute: PostsRouteWithChildren,
  OrgsOrgIdUsersUserIdRoute: OrgsOrgIdUsersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
