#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import csv
import unicodedata
from collections import Counter
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List


LEGACY_TO_ENGLISH_COLUMNS = {
    "arquivo": "file",
    "block_inicio": "block_start",
    "autores_evidencia": "evidence_authors",
    "tipo_convite": "invite_type",
    "resumo_llm": "llm_summary",
}


def normalize_text(value: str) -> str:
    normalized = unicodedata.normalize("NFKD", value)
    ascii_only = "".join(ch for ch in normalized if not unicodedata.combining(ch))
    return " ".join(ascii_only.casefold().split())


def parse_authors(raw_value: str) -> List[str]:
    if not raw_value.strip():
        return []
    return [author.strip() for author in raw_value.split(",") if author.strip()]


def extract_day(raw_value: str) -> str:
    raw_value = raw_value.strip()
    if not raw_value:
        return ""

    try:
        return datetime.strptime(raw_value, "%d/%m/%Y %H:%M").strftime("%Y-%m-%d")
    except ValueError:
        return raw_value


def get_row_value(row: Dict[str, str], column_name: str) -> str:
    if column_name in row:
        return row.get(column_name, "")

    legacy_name = next(
        (legacy for legacy, english in LEGACY_TO_ENGLISH_COLUMNS.items() if english == column_name),
        None,
    )
    if legacy_name:
        return row.get(legacy_name, "")

    return ""


def analyze_csv(path: Path, target_name: str = "") -> Dict[str, Any]:
    interaction_counts: Counter[str] = Counter()
    matched_rows = []
    target_norm = normalize_text(target_name) if target_name else ""
    counted_author_days = set()

    with open(path, "r", encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)

        for row in reader:
            authors = parse_authors(get_row_value(row, "evidence_authors"))
            day_key = extract_day(get_row_value(row, "block_start"))
            for author in authors:
                author_day_key = (author, day_key)
                if author_day_key not in counted_author_days:
                    interaction_counts[author] += 1
                    counted_author_days.add(author_day_key)

            if target_norm and any(normalize_text(author) == target_norm for author in authors):
                matched_rows.append(
                    {
                        "file": str(path),
                        "block_id": row.get("block_id", ""),
                        "block_start": get_row_value(row, "block_start"),
                        "day": day_key,
                        "evidence_authors": get_row_value(row, "evidence_authors"),
                        "invite_type": get_row_value(row, "invite_type"),
                        "llm_summary": get_row_value(row, "llm_summary"),
                    }
                )

    least_interactions = min(interaction_counts.values()) if interaction_counts else 0
    least_active_members = sorted(
        [author for author, count in interaction_counts.items() if count == least_interactions]
    )

    return {
        "file": str(path),
        "interaction_counts": interaction_counts,
        "least_interactions": least_interactions,
        "least_active_members": least_active_members,
        "matched_rows": matched_rows,
    }


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Analyzes event CSVs and counts interactions per member using the "
            "'evidence_authors' field."
        )
    )
    parser.add_argument("input", nargs="+", help="One or more CSV files generated by the classifier")
    parser.add_argument(
        "--name",
        help="Specific name to search for in the 'evidence_authors' column (case/accent-insensitive)",
    )
    parser.add_argument(
        "--top",
        type=int,
        default=10,
        help="Number of members to show in the ranking. Default: 10",
    )
    args = parser.parse_args()

    aggregate_counts: Counter[str] = Counter()
    aggregate_matches = []

    for input_path in args.input:
        result = analyze_csv(Path(input_path), target_name=args.name or "")
        aggregate_counts.update(result["interaction_counts"])
        aggregate_matches.extend(result["matched_rows"])

        print(f"\nFile: {result['file']}")
        print(f"Distinct members: {len(result['interaction_counts'])}")
        if result["interaction_counts"]:
            print("Top interactions:")
            for author, count in result["interaction_counts"].most_common(args.top):
                print(f"  {author}: {count}")

            print(
                f"Lowest number of days with interaction: {result['least_interactions']} | "
                f"Members: {', '.join(result['least_active_members'])}"
            )
        else:
            print("No interactions found in 'evidence_authors'.")

    if len(args.input) > 1:
        print("\nCombined")
        print(f"Distinct members: {len(aggregate_counts)}")
        if aggregate_counts:
            print("Top interactions:")
            for author, count in aggregate_counts.most_common(args.top):
                print(f"  {author}: {count}")

            least_interactions = min(aggregate_counts.values())
            least_active_members = sorted(
                [author for author, count in aggregate_counts.items() if count == least_interactions]
            )
            print(
                f"Lowest number of days with interaction: {least_interactions} | "
                f"Members: {', '.join(least_active_members)}"
            )

    if args.name:
        print(f"\nMatches for '{args.name}': {len(aggregate_matches)}")
        for row in aggregate_matches:
            print(
                f"  {row['file']} | block {row['block_id']} | {row['block_start']} | day {row['day']} | "
                f"{row['evidence_authors']} | {row['invite_type']} | {row['llm_summary']}"
            )


if __name__ == "__main__":
    main()
